import { createContext, useContext } from "react";

export const MarkdownLanguage = createContext<"zh-CN" | "en">("en");
const chinese = {
 "Could not save preferences. Try again.": "无法保存设置，请重试。",
 "Could not reload this document. Try again.": "无法重新载入文档，请重试。",
 "Resolve the document’s unsaved changes, then try again.": "请先处理文档中未保存的更改，再重试。",
 "Could not close settings. Try again.": "无法关闭设置，请重试。",
 "Could not open settings. Try again.": "无法打开设置，请重试。",
 "Done": "完成",
 "Editing": "编辑",
 "Source format": "语法格式",
 "Code blocks": "代码块",
 "Rendering": "渲染",
 "Could not open menu. Try again.": "无法打开菜单，请重试。",
	"Markdown preferences": "Markdown 设置",
	"Show block markers while editing": "编辑时显示块标记",
	"Sequence style": "时序图样式",
	Simple: "简洁",
	"Hand drawn": "手绘",
	"Suggest emoji while typing": "输入时建议表情符号",
	"Render $…$ as inline math": "将 $…$ 显示为行内公式",
	"Automatically recognize links": "自动识别链接",
	"Strict Markdown syntax": "使用严格 Markdown 语法",
	"Render GitHub alerts": "显示 GitHub 提示块",
	"Render diagrams": "显示图表",
	"Render ==…== as highlight": "将 ==…== 显示为高亮",
	"Render ~…~ as subscript": "将 ~…~ 显示为下标",
	"Render ^…^ as superscript": "将 ^…^ 显示为上标",
	"Reloads this document after saving. Undo history will reset.":
		"保存后重新载入文档，撤销记录将被清空。",
	"Apply to document": "应用到文档",
	"Applies to Markdown views. Does not change document content.":
		"用于 Markdown 视图，不更改文档内容。",
	"New heading style": "新标题样式",
	"# Heading": "# 标题",
	"Setext (===)": "下划线式（===）",
	"# Heading #": "# 标题 #",
	"Setext matched to text width": "下划线与标题等宽",
	"New bullet marker": "新列表项目符号",
	"New list numbering": "新列表编号",
	"List and quote indentation": "列表与引用缩进",
	Automatic: "自动",
	"2 spaces": "2 个空格",
	"3 spaces": "3 个空格",
	"4 spaces": "4 个空格",
	"5 spaces": "5 个空格",
	Tab: "制表符",
	"-": "-",
	"+": "+",
	"*": "*",
	"1. 2. 3.": "1. 2. 3.",
	"1. 1. 1.": "1. 1. 1.",
	"Align text after list and quote markers": "对齐列表和引用标记后的文字",
	"Used by formatting commands. Typed markers and existing source keep their style. Setext applies to headings 1 and 2 outside lists.":
		"用于格式命令，保留手动输入和已有源码的样式。下划线式仅用于列表外的一、二级标题。",
	"Code indentation": "代码缩进",
	columns: "列",
	"Pair brackets and quotes in code": "自动配对代码中的括号和引号",
	"Show code line numbers": "显示代码行号",
	"Wrap code lines": "代码自动换行",
	"Reindent code with Shift+Tab": "使用 Shift+Tab 重新缩进代码",
	"Wrapping and indentation also apply to block formula and HTML source. Line numbers also apply to block formulas.":
		"换行和缩进也用于公式块与 HTML 源码，公式块也可显示行号。",
	"Default code language": "默认代码语言",
	"Plain text": "纯文本",
	"Enter a language without backticks or tildes.":
		"语言名称不能包含反引号或波浪号。",
	"Use last used language": "使用上次的语言",
	"Apply default language when": "使用默认语言的时机",
	"Typing a code fence": "输入代码围栏时",
	"Using a command": "使用命令时",
	Either: "两种情况都使用",
	"Open in Blabla": "在 Blabla 中打开",
	"Reference label": "引用标签",
	"Edit definition": "编辑定义",
	"Enter a label without brackets.": "引用标签不能包含方括号。",
	"Unsupported link address.": "此链接地址不受支持，请检查地址格式。",

	"Text style": "正文样式",
	Body: "正文",
	More: "更多",
	Insert: "插入",
	Lists: "列表",
	"Heading 1": "一级标题",
	"Heading 2": "二级标题",
	"Heading 3": "三级标题",
	"Heading 4": "四级标题",
	"Heading 5": "五级标题",
	"Heading 6": "六级标题",
	"Bullet list": "无序列表",
	"Ordered list": "有序列表",
	"Task list": "任务列表",
	Blockquote: "引用",
	"Code block": "代码块",
	Bold: "粗体",
	Italic: "斜体",
	Strike: "删除线",
	Code: "行内代码",
	Underline: "下划线",
	Highlight: "高亮",
	Subscript: "下标",
	Superscript: "上标",
	"Clear formatting": "清除格式",
	"Text colors": "文字颜色",
	"Text font": "字体",
	Link: "链接",
	Table: "表格",
	"Insert alert": "提示块",
	Note: "备注",
	Tip: "提示",
	Important: "重要",
	Warning: "警告",
	Caution: "注意",
	Undo: "撤销",
	Redo: "重做",
	"Text color": "文字颜色",
	"Background color": "背景颜色",
	"Font family": "字体",
	"Font size": "字号",
	Apply: "应用",
	Reset: "恢复默认",
	"Apply text color": "应用文字颜色",
	"Reset text color": "恢复默认文字颜色",
	"Apply background color": "应用背景颜色",
	"Reset background color": "恢复默认背景颜色",
	"Apply font family": "应用字体",
	"Reset font family": "恢复默认字体",
	"Apply font size": "应用字号",
	"Reset font size": "恢复默认字号",
	"Enter a valid CSS color.": "请输入有效颜色，例如 #ff0000。",
	"Enter a valid CSS font family.": "请输入有效字体名称，例如 Georgia。",
	"Enter a valid CSS font size.": "请输入有效字号，例如 24px。",
	"Font context": "继承的字体样式",
	Rows: "行数",
	Columns: "列数",
	"Table rows": "表格行数",
	"Table columns": "表格列数",
	"Resize table": "调整表格大小",
	"Insert table": "插入表格",
	"Insert row above": "在上方插入行",
	"Insert row below": "在下方插入行",
	"Insert column left": "在左侧插入列",
	"Insert column right": "在右侧插入列",
	"Move row up": "上移行",
	"Move row down": "下移行",
	"Move column left": "左移列",
	"Move column right": "右移列",
	"Align column left": "列左对齐",
	"Align column center": "列居中",
	"Align column right": "列右对齐",
	"Delete row": "删除行",
	"Delete column": "删除列",
	"Delete table": "删除表格",
	"Link address": "链接地址",
	"Link title": "链接标题",
	"Apply link": "应用链接",
	"Remove link": "移除链接",
	"Open link": "打开链接",
	"Paste a link...": "输入或粘贴链接",
	"Title (optional)": "标题（可选）",
	"Selected text tools": "文字格式",
	"Table tools": "表格工具",
} as const;
export type ToolText = keyof typeof chinese;
export function useToolCopy() {
	const language = useContext(MarkdownLanguage);
	return (text: ToolText) => (language === "zh-CN" ? (chinese[text] ?? text) : text);
}
